CREATE TABLE AmenityImages(
    ImageID INT IDENTITY PRIMARY KEY,
    Image VARCHAR(150)
)

CREATE TABLE Amenities(
    AmenityID INT IDENTITY PRIMARY KEY,
    ParkID VARCHAR(6) FOREIGN KEY REFERENCES Parks(ParkID),
    Amenity VARCHAR(100),
    Quantity INT,
    ImageID INT FOREIGN KEY REFERENCES AmenityImages(ImageID)
)

INSERT INTO AmenityImages(Image)
VALUES
('/images/AmenityImages/boatingInstructionSafteyCenter.png'),
('/images/AmenityImages/restrooms.png'),
('/images/AmenityImages/classroom.png'),
('/images/AmenityImages/library.png'),
('/images/AmenityImages/computerLabs.png'),
('/images/AmenityImages/exhibitArea.png'),
('/images/AmenityImages/museum.png'),
('/images/AmenityImages/historicalValue.png'),
('/images/AmenityImages/civicArt.png'),
('/images/AmenityImages/memorial.png'),
('/images/AmenityImages/theater.png'),
('/images/AmenityImages/giftShop.png'),
('/images/AmenityImages/sheriffSubStation.png'),
('/images/AmenityImages/picnicShelter.png'),
('/images/AmenityImages/groupPicnic.png'),
('/images/AmenityImages/amphitheater.png'),
('/images/AmenityImages/ticketBooth.png'),
('/images/AmenityImages/maintenanceYardBldg.png'),
('/images/AmenityImages/softballField.png'),
('/images/AmenityImages/baseball.png'),
('/images/AmenityImages/soccerField.png'),
('/images/AmenityImages/tennisCourt.png'),
('/images/AmenityImages/basketballFullCourt.png'),
('/images/AmenityImages/volleyballSand.png'),
('/images/AmenityImages/swimmingPool.png'),
('/images/AmenityImages/SplashPad.png'),
('/images/AmenityImages/FitnessZone.png'),
('/images/AmenityImages/BoatingArea.png'),
('/images/AmenityImages/lakes.png'),
('/images/AmenityImages/BoatRental.png'),
('/images/AmenityImages/SWIM_BEACH.png'),
('/images/AmenityImages/SailingArea.png'),
('/images/AmenityImages/FishingLake.png'),
('/images/AmenityImages/HorseTrail.png'),
('/images/AmenityImages/HikingTrail.png'),
('/images/AmenityImages/BicycleTrail.png'),
('/images/AmenityImages/HorseshoePit.png'),
('/images/AmenityImages/CommunityGarden.png'),
('/images/AmenityImages/ControlAirplaneArea.png'),
('/images/AmenityImages/AnimalExhibit.png'),
('/images/AmenityImages/ShootingRange.png'),
('/images/AmenityImages/PlayArea2-5YRS.png'),
('/images/AmenityImages/ChildrensPlayArea.png'),
('/images/AmenityImages/campingTent.png'),
('/images/AmenityImages/campingGroups.png'),
('/images/AmenityImages/BBQ.png'),
('/images/AmenityImages/OutdoorKitchen.png'),
('/images/AmenityImages/PicnicTables.png'),
('/images/AmenityImages/banquetRoom.png'),
('/images/AmenityImages/OutdoorStage.png'),
('/images/AmenityImages/concessionStands.png');


INSERT INTO Amenities(ParkID, Amenity, Quantity, ImageID)
VALUES
('CAST', 'Boat Instr. Safety Ctr.', 1, 1),
('CAST', 'Restrooms', 20, 2),
('CAST', 'Concession Stand', 1, 51),
('CAST', 'Classroom', 4, 3),
('CAST', 'Historical Value', 1, 8),
('CAST', 'Civic Art', 1, 9),
('CAST', 'Sheriff Sub Station', 1, 13),
('CAST', 'Picnic Shelter', 15, 14),
('CAST', 'Group Picnic Shelter', 25, 15),
('CAST', 'Ticket Booth', 1, 17),
('CAST', 'Maintenance Yard Bldg', 1, 18),
('CAST', 'Wi-Fi', 1, 1),
('CAST', 'Boating Area', 1, 28),
('CAST', 'Lake', 2, 29),
('CAST', 'Boat Rental', 1, 30),
('CAST', 'Swimming Beach', 1, 31),
('CAST', 'Sailing Area', 1, 32),
('CAST', 'Fishing Lake', 1, 33),
('CAST', 'Trail Staging Areas', 1, 1),
('CAST', 'Multi-Use Trail', 1, 1),
('CAST', 'Horse Trail', 1, 34),
('CAST', 'Hiking Trail', 1, 35),
('CAST', 'Bicycle Trail', 1, 36),
('CAST', 'Horseshoe Pit', 4, 37),
('CAST', 'BMX Track', 1, 1),
('CAST', 'Control Airplane Area', 1, 39),
('CAST', 'Play Area 2-5 Years', 3, 42),
('CAST', 'Children Play Area', 3, 43),
('CAST', 'Camping Tent', 1, 44),
('CAST', 'Camping - Group', 1, 45),
('CAST', 'Camping - RV', 1, 1),
('CAST', 'RV Dump Station', 1, 1),
('CAST', 'Showers', 1, 1),
('CAST', 'BBQs', 1, 46),
('CAST', 'Outdoor Kitchen', 1, 47),
('CAST', 'Picnic Tables', 1, 48),
('CAST', 'Banners/Kiosks', 1, 1),
('CAST', 'Educational Signage', 1, 1),
('CAST', 'Maintenance Yard', 1, 1),
('CAST', 'Security Lighting', 1, 1),
('CAST', 'Parking Onsite', 1, 1),
('CAST', 'Parking Over Sized Vehicle', 1, 1),
('BONE', 'Restrooms', 27, 2),
('BONE', 'Concession Stand', 1, 51),
('BONE', 'Historical Value', 1, 8),
('BONE', 'Civic Art', 6, 9),
('BONE', 'Memorial', 1, 10),
('BONE', 'Group Picnic Shelter', 17, 15),
('BONE', 'Ticket Booth', 1, 17),
('BONE', 'Maintenance Yard Bldg', 1, 18),
('BONE', 'Trash Enclosure', 1, 1),
('BONE', 'Baseball Field', 1, 1),
('BONE', 'Softball Field', 6, 19),
('BONE', 'Soccer Field', 10, 21),
('BONE', 'Wi-Fi', 1, 1),
('BONE', 'Tennis Court', 16, 22),
('BONE', 'Volleyball Sand', 1, 24),
('BONE', 'Fitness Zone', 2, 27),
('BONE', 'Boating Area', 1, 28),
('BONE', 'Lake', 3, 29),
('BONE', 'Boat Rental', 1, 30),
('BONE', 'Fishing Lake', 1, 33),
('BONE', 'Trail Staging Areas', 1, 1),
('BONE', 'Multi-Use Trail', 1, 1),
('BONE', 'Horse Trail', 1, 34),
('BONE', 'Hiking Trail', 1, 35),
('BONE', 'Bicycle Trail', 1, 36),
('BONE', 'Horseshoe Pit', 2, 37),
('BONE', 'Community Garden', 1, 38),
('BONE', 'Specialty Garden', 1, 1),
('BONE', 'Control Airplane Area', 1, 39),
('BONE', 'Model Boat Area', 1, 1),
('BONE', 'Shooting Range', 1, 41),
('BONE', 'Children Play Area', 7, 43),
('BONE', 'BBQs', 1, 46),
('BONE', 'Picnic Tables', 1, 48),
('BONE', 'Drinking Fountains', 1, 1),
('BONE', 'Telephone', 1, 1),
('BONE', 'Banners/Kiosks', 1, 1),
('BONE', 'Educational Signage', 1, 1),
('BONE', 'Outdoor Stage', 1, 50),
('BONE', 'Maintenance Yard', 1, 1),
('BONE', 'Security Lighting', 1, 1),
('BONE', 'Parking Onsite', 1, 1),
('BONE', 'Disc Golf No. of Holes', 18, 1),
('BONE', 'BMX Track', 1, 1),
('SFD', 'Restrooms', 16, 2),
('SFD', 'Concession Stand', 2, 51),
('SFD', 'Sheriff Sub Station', 1, 13),
('SFD', 'Picnic Shelter', 110, 14),
('SFD', 'Group Picnic Shelter', 6, 15),
('SFD', 'Ticket Booth', 1, 17),
('SFD', 'Maintenance Yard Bldg', 1, 18),
('SFD', 'Softball Field', 1, 19), 
('SFD', 'Boating Area', 1, 28),
('SFD', 'Lake', 1, 29),
('SFD', 'Boat Rental', 1, 30),
('SFD', 'Swimming Beach', 1, 31),
('SFD', 'Sailing Area', 1, 32),
('SFD', 'Fishing Lake', 1, 33),
('SFD', 'Trail Staging Areas', 1, 1),
('SFD', 'Multi-Use Trail', 1, 1),
('SFD', 'Horse Trail', 1, 34),
('SFD', 'Hiking Trail', 1, 35),
('SFD', 'Bicycle Trail', 1, 36),
('SFD', 'Horseshoe Pit', 1, 37),
('SFD', 'Play Area 2-5 Years', 1, 42),
('SFD', 'Children Play Area', 3, 43),
('SFD', 'Camping - RV', 1, 1),
('SFD', 'BBQs', 1, 46),
('SFD', 'Outdoor Kitchen', 1, 47),
('SFD', 'Picnic Tables', 1, 48),
('SFD', 'Drinking Fountains', 1, 1),
('SFD', 'Telephone', 1, 1),
('SFD', 'Vending Machine', 1, 1),
('SFD', 'Banners/Kiosks', 1, 1),
('SFD', 'Educational Signage', 1, 1),
('SFD', 'Maintenance Yard', 1, 1),
('SFD', 'Security Lighting', 1, 1),
('SFD', 'Parking Onsite', 1, 1),
('WNRA', 'Nature Center', 1, 1),
('WNRA', 'Restrooms', 9, 2),
('WNRA', 'Concession Stand', 1, 51),
('WNRA', 'Group Picnic Shelter', 5, 15),
('WNRA', 'Maintenance Yard Bldg', 1, 18),
('WNRA', 'Trash Enclosure', 1, 1),
('WNRA', 'Wi-Fi', 1, 1),
('WNRA', 'Volleyball Sand', 2, 24),
('WNRA', 'Splash Pad', 1, 26),
('WNRA', 'Fitness Zone', 1, 27),
('WNRA', 'Boating Area', 1, 28),
('WNRA', 'Lake', 1, 29),
('WNRA', 'Boat Rental', 1, 30),
('WNRA', 'Swimming Beach', 1, 31),
('WNRA', 'Sailing Area', 1, 32),
('WNRA', 'Fishing Lake', 1, 33),
('WNRA', 'Bicycle Trail', 1, 36),
('WNRA', 'Wildlife Sanctuary', 1, 1),
('WNRA', 'Play Area 2-5 Years', 1, 42),
('WNRA', 'Children Play Area', 2, 43),
('WNRA', 'Camping - Group', 1, 45),
('WNRA', 'Showers', 1, 1),
('WNRA', 'BBQs', 1, 46),
('WNRA', 'Picnic Tables', 1, 48),
('WNRA', 'Drinking Fountains', 1, 1),
('WNRA', 'Telephone', 1, 1),
('WNRA', 'Vending Machine', 1, 1),
('WNRA', 'Educational Signage', 1, 1),
('WNRA', 'Maintenance Yard', 1, 1),
('WNRA', 'Security Lighting', 1, 1),
('WNRA', 'Parking Onsite', 1, 1),
('SCHA', 'Restrooms', 1, 2),
('SCHA', 'Historical Value', 1, 8),
('SCHA', 'Memorial', 1, 10),
('SCHA', 'Picnic Shelter', 2, 14),
('SCHA', 'Group Picnic Shelter', 5, 15),
('SCHA', 'Amphitheater', 1, 16),
('SCHA', 'Maintenance Yard Bldg', 1, 18),
('SCHA', 'Trash Enclosure', 1, 1),
('SCHA', 'Soccer Field', 2, 21),
('SCHA', 'Tennis Court', 2, 22),
('SCHA', 'Fitness Zone', 1, 27),
('SCHA', 'Trail Staging Areas', 1, 1),
('SCHA', 'Multi-Use Trail', 1, 1),
('SCHA', 'Horse Trail', 1, 34),
('SCHA', 'Hiking Trail', 1, 35),
('SCHA', 'Bicycle Trail', 1, 36),
('SCHA', 'Play Area 2-5 Years', 1, 42),
('SCHA', 'Children Play Area', 2, 43),
('SCHA', 'Camping - Group', 1, 45),
('SCHA', 'BBQs', 1, 46),
('SCHA', 'Outdoor Kitchen', 1, 47),
('SCHA', 'Picnic Tables', 1, 48),
('SCHA', 'Drinking Fountains', 1, 1),
('SCHA', 'Telephone', 1, 1),
('SCHA', 'Vending Machine', 1, 1),
('SCHA', 'Banners/Kiosks', 1, 1),
('SCHA', 'Outdoor Stage', 1, 50),
('SCHA', 'Maintenance Yard', 1, 1),
('SCHA', 'Security Lighting', 1, 1),
('SCHA', 'Parking Onsite', 1, 1);

