
CREATE TABLE ParkImages (
    ImageID INT IDENTITY PRIMARY KEY,
    ParkID varchar(6) FOREIGN KEY REFERENCES Parks(ParkID),
    ImagePath VARCHAR(255)
)

INSERT INTO ParkImages(ParkID, ImagePath)
VALUES
('BONE', '/images/BoneliCA/BR6I1564.jpg'),
('BONE', '/images/BoneliCA/BR6I1601.jpg'),
('BONE', '/images/BoneliCA/BR6I1617.jpg'),
('BONE', '/images/BoneliCA/BR6I1621.jpg'),
('BONE', '/images/BoneliCA/BR6I1630.jpg'),
('BONE', '/images/BoneliCA/BR6I1634.jpg'),
('BONE', '/images/BoneliCA/BR6I1661.jpg'),
('BONE', '/images/BoneliCA/BR6I1702.jpg'),
('BONE', '/images/BoneliCA/BR6I1707.jpg'),
('BONE', '/images/BoneliCA/BR6I1721.jpg'),
('SFD', '/images/SantaFeDamCA/BR6I2653.jpg'),
('SFD', '/images/SantaFeDamCA/BR6I2662.jpg'),
('SFD', '/images/SantaFeDamCA/BR6I2682.jpg'),
('SFD', '/images/SantaFeDamCA/BR6I2721.jpg'),
('SFD', '/images/SantaFeDamCA/BR6I2751.jpg'),
('SFD', '/images/SantaFeDamCA/BR6I2811.jpg'),
('SFD', '/images/SantaFeDamCA/BR6I2820.jpg'),
('SFD', '/images/SantaFeDamCA/BR6I2840.jpg'),
('SFD', '/images/SantaFeDamCA/BR6I2854.jpg'),
('SFD', '/images/SantaFeDamCA/BR6I2931.jpg'),
('SFD', '/images/SantaFeDamCA/BR6I2978.jpg'),
('SCHA', '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-1-of-52.jpg'),
('SCHA', '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-3-of-52.jpg'),
('SCHA', '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-4-of-52.jpg'),
('SCHA', '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-7-of-52.jpg'),
('SCHA', '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-8-of-52.jpg'),
('SCHA', '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-22-of-52.jpg'),
('SCHA', '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-25-of-52.jpg'),
('SCHA', '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-28-of-52.jpg'),
('SCHA', '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-36-of-52.jpg'),
('SCHA', '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-42-of-52.jpg'),
('HAHN', '/images/KennethHahnStateRecreationAreaCA/BR6I8004.jpg'),
('HAHN', '/images/KennethHahnStateRecreationAreaCA/BR6I8028.jpg'),
('HAHN', '/images/KennethHahnStateRecreationAreaCA/BR6I8044.jpg'),
('HAHN', '/images/KennethHahnStateRecreationAreaCA/BR6I8115.jpg'),
('HAHN', '/images/KennethHahnStateRecreationAreaCA/BR6I8123.jpg'),
('HAHN', '/images/KennethHahnStateRecreationAreaCA/BR6I8128.jpg'),
('HAHN', '/images/KennethHahnStateRecreationAreaCA/BR6I8168.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/BR6I9848.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/BR6I9913.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/BR6I9932.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/BR6I9976.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/BR6I9983.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-1-of-10.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-2-of-10.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-3-of-10.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-4-of-10.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-5-of-10.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-6-of-10.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-7-of-10.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-8-of-10.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-9-of-10.jpg'),
('SFPL', '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-10-of-10.jpg'),
('ROW', '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-2-of-17.jpg'),
('ROW', '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-3-of-17.jpg'),
('ROW', '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-4-of-17.jpg'),
('ROW', '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-6-of-17.jpg'),
('ROW', '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-7-of-17.jpg'),
('ROW', '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-8-of-17.jpg'),
('ROW', '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-12-of-17.jpg'),
('ROW', '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-13-of-17.jpg'),
('ROW', '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-14-of-17.jpg'),
('ROW', '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-15-of-17.jpg'),
('FRND', '/images/DeaneDanaPark/BR6I1461.jpg'),
('FRND', '/images/DeaneDanaPark/BR6I1448.jpg'),
('FRND', '/images/DeaneDanaPark/BR6I1423.jpg'),
('FRND', '/images/DeaneDanaPark/BR6I1404.jpg'),
('FRND', '/images/DeaneDanaPark/BR6I1376.jpg'),
('FRND', '/images/DeaneDanaPark/BR6I1344.jpg'),
('FRND', '/images/DeaneDanaPark/BR6I1340.jpg'),
('FRND', '/images/DeaneDanaPark/BR6I1337.jpg'),
('FARN', '/images/CharlesS.FarnsworthPark/BR6I7226.jpg'),
('FARN', '/images/CharlesS.FarnsworthPark/BR6I7229.jpg'),
('FARN', '/images/CharlesS.FarnsworthPark/BR6I7237.jpg'),
('FARN', '/images/CharlesS.FarnsworthPark/BR6I7241.jpg'),
('FARN', '/images/CharlesS.FarnsworthPark/BR6I7245.jpg'),
('FARN', '/images/CharlesS.FarnsworthPark/BR6I7249.jpg'),
('FARN', '/images/CharlesS.FarnsworthPark/BR6I7277.jpg'),
('FARN', '/images/CharlesS.FarnsworthPark/BR6I7290.jpg'),
('FARN', '/images/CharlesS.FarnsworthPark/BR6I7297.jpg'),
('FARN', '/images/CharlesS.FarnsworthPark/BR6I7312.jpg')








INSERT INTO ParkImages(ParkID, ImagePath)
VALUES
(3, '/images/BoneliCA/BR6I1564.jpg'),
(3, '/images/BoneliCA/BR6I1601.jpg'),
(3, '/images/BoneliCA/BR6I1617.jpg'),
(3, '/images/BoneliCA/BR6I1621.jpg'),
(3, '/images/BoneliCA/BR6I1630.jpg'),
(3, '/images/BoneliCA/BR6I1634.jpg'),
(3, '/images/BoneliCA/BR6I1661.jpg'),
(3, '/images/BoneliCA/BR6I1702.jpg'),
(3, '/images/BoneliCA/BR6I1707.jpg'),
(3, '/images/BoneliCA/BR6I1721.jpg'),
(4, '/images/SantaFeDamCA/BR6I2653.jpg'),
(4, '/images/SantaFeDamCA/BR6I2662.jpg'),
(4, '/images/SantaFeDamCA/BR6I2682.jpg'),
(4, '/images/SantaFeDamCA/BR6I2721.jpg'),
(4, '/images/SantaFeDamCA/BR6I2751.jpg'),
(4, '/images/SantaFeDamCA/BR6I2811.jpg'),
(4, '/images/SantaFeDamCA/BR6I2820.jpg'),
(4, '/images/SantaFeDamCA/BR6I2840.jpg'),
(4, '/images/SantaFeDamCA/BR6I2854.jpg'),
(4, '/images/SantaFeDamCA/BR6I2931.jpg'),
(4, '/images/SantaFeDamCA/BR6I2978.jpg'),
(5, '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-1-of-52.jpg'),
(5, '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-3-of-52.jpg'),
(5, '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-4-of-52.jpg'),
(5, '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-7-of-52.jpg'),
(5, '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-8-of-52.jpg'),
(5, '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-22-of-52.jpg'),
(5, '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-25-of-52.jpg'),
(5, '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-28-of-52.jpg'),
(5, '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-36-of-52.jpg'),
(5, '/images/SchabarumCA/Edited_PeterFSchabarumRegionalPark-42-of-52.jpg'),
(6, '/images/KennethHahnStateRecreationAreaCA/BR6I8004.jpg'),
(6, '/images/KennethHahnStateRecreationAreaCA/BR6I8028.jpg'),
(6, '/images/KennethHahnStateRecreationAreaCA/BR6I8044.jpg'),
(6, '/images/KennethHahnStateRecreationAreaCA/BR6I8115.jpg'),
(6, '/images/KennethHahnStateRecreationAreaCA/BR6I8123.jpg'),
(6, '/images/KennethHahnStateRecreationAreaCA/BR6I8128.jpg'),
(6, '/images/KennethHahnStateRecreationAreaCA/BR6I8168.jpg'),
(7, '/images/SFVPoolRecCenterCA/BR6I9848.jpg'),
(7, '/images/SFVPoolRecCenterCA/BR6I9913.jpg'),
(7, '/images/SFVPoolRecCenterCA/BR6I9932.jpg'),
(7, '/images/SFVPoolRecCenterCA/BR6I9976.jpg'),
(7, '/images/SFVPoolRecCenterCA/BR6I9983.jpg'),
(7, '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-1-of-10.jpg'),
(7, '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-2-of-10.jpg'),
(7, '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-3-of-10.jpg'),
(7, '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-4-of-10.jpg'),
(7, '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-5-of-10.jpg'),
(7, '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-6-of-10.jpg'),
(7, '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-7-of-10.jpg'),
(7, '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-8-of-10.jpg'),
(7, '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-9-of-10.jpg'),
(7, '/images/SFVPoolRecCenterCA/Edited_-SanFernandoRecreationPark-10-of-10.jpg'),
(8, '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-2-of-17.jpg'),
(8, '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-3-of-17.jpg'),
(8, '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-4-of-17.jpg'),
(8, '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-6-of-17.jpg'),
(8, '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-7-of-17.jpg'),
(8, '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-8-of-17.jpg'),
(8, '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-12-of-17.jpg'),
(8, '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-13-of-17.jpg'),
(8, '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-14-of-17.jpg'),
(8, '/images/RowlandHeightsCommunityCenterCA/2_Rowland_Heights_Park-15-of-17.jpg’),
(13, '/images/DeaneDanaPark/BR6I1461.jpg'),
(13, '/images/DeaneDanaPark/BR6I1448.jpg'),
(13, '/images/DeaneDanaPark/BR6I1423.jpg'),
(13, '/images/DeaneDanaPark/BR6I1404.jpg'),
(13, '/images/DeaneDanaPark/BR6I1376.jpg'),
(13, '/images/DeaneDanaPark/BR6I1344.jpg'),
(13, '/images/DeaneDanaPark/BR6I1340.jpg'),
(13, '/images/DeaneDanaPark/BR6I1337.jpg’),
(14, '/images/CharlesS.FarnsworthPark/BR6I7226.jpg'),
(14, '/images/CharlesS.FarnsworthPark/BR6I7229.jpg'),
(14, '/images/CharlesS.FarnsworthPark/BR6I7237.jpg'),
(14, '/images/CharlesS.FarnsworthPark/BR6I7241.jpg'),
(14, '/images/CharlesS.FarnsworthPark/BR6I7245.jpg'),
(14, '/images/CharlesS.FarnsworthPark/BR6I7249.jpg'),
(14, '/images/CharlesS.FarnsworthPark/BR6I7277.jpg'),
(14, '/images/CharlesS.FarnsworthPark/BR6I7290.jpg'),
(14, '/images/CharlesS.FarnsworthPark/BR6I7297.jpg'),
(14, '/images/CharlesS.FarnsworthPark/BR6I7312.jpg')